#!/bin/bash

# for Ubuntu, obvs, naybe apt-get intsall -y ubuntu-wallpapers* is better 

FLAGS=""
space=""

for version in karmic lucid maverick natty oneiric precise quantal raring saucy trusty utopic vivid wily
do
	FLAGS=${FLAGS}${space}ubuntu-wallpapers-${version}
	# this is wrong
	space=" "
done

apt-get install -y $FLAGS
