#!/bin/bash

# this script starts moonbridge & liquid feedback

# it needs an sudo/su statment

/opt/moonbridge/moonbridge /opt/webmcp/bin/mcp.lua /opt/mcp /opt/liquid_feedback_frontend/ main myconfig
