#!/bin/bash

# this program needs time and update db

# amended 15/4/2019, final if test amended

if [ `whoami` != "root" ]
then
	echo neds to run as root
	exit 1
fi


echo `date +%c` updatedb starts
echo
time updatedb
echo `date +%c` updatedb ends
echo
if [[ $1 -eq "--with-logger" ]]
then
	logger "updatedb run by cron"
fi
