#!/bin/bash

# Author Dave Levy	Date 30 Aug 2016 	Version 1.2

# obtains the ip address of a given ethernet device, via menu or from the cli
# the ip address is echoed via stdout

# -h help, -m menu, -d a debug mode enhanced diagnostics  or -b which allows hte naming
#	of the device. 

# i.e. using -m offers you a list of devices from which you can choose or
# -b allows the specification of the device from which the ip address is to be
# taken

# needs to run as root, could do with a clean to delete the persistance file 
# and a switch to merely cat the file

# why not use ip -4 or my showsysip script


ERROR="Error in command line arguments"
USAGE="$(basename $0) [ -h | -m | -d | -b device ]"

debug=/bin/false
debugecho()
{
	if [ ${debug} == true ]
	then
		echo $*
	fi
}


while getopts "hmdb:" arg
do
case $arg in
m)	devices=$(ifconfig -a -s | cut -f1 -d" ")
	set DEVICES

	for i in $devices
	do
		if [[ $i == "Iface" ]];then
			:
		else
			DEVICES="${DEVICES} ${i}"
		fi
	done

	echo "Select the Device Name for which IP is to be stored"
	select PORTNAME in $DEVICES
	do
		break
	done
	echo $PORTNAME set in menu mode
	;;
b)	PORTNAME=${OPTARG}
	# it would be good to test that $PORTNAME actuall named an valid device
	debugecho $PORTNAME set in batch mode reported by debug echo
	;;
d)	debug=true
	debugecho debug set to $debug, reported by debugecho
	;;
h)	echo ${USAGE}
	exit 
	;;
help)	echo ${USAGE}
	exit 
	;;
*)	echo ${ERROR}; exit 1
	;;
esac
done


#PORTNAME=enp0s8
#debugecho Portname rest to $PORTNAME by default code path

# this could be parameterised a -o flag

PERSISTANCE="/usr/local/etc/.myip"

debugecho the persistance file, $PERSISTANCE exists
ifconfig $PORTNAME | grep "inet addr" | cut -f2 -d":" | cut -f1 -d" " > ${PERSISTANCE}
cat ${PERSISTANCE}
