#!/bin/bash
set -x

# if Raspian

export DISPLAY=:10.0
LOGDIR=/opt/local/logs

# not sure about nohup, and ksar-latest is a link
nohup java -jar /opt/java/ksar-latest.jar > ${LOGDIR}/ksar.log 2>&1 &


