#!/bin/bash

# This makes source code folders under where you are

# This installs opentracker, only needed if yoou want to run an index

USAGE="$0 [install|remove|makeenv]"

HERE=`pwd`

case $1 in
install) :
	cvs -d :pserver:cvs@cvs.fefe.de:/cvs -z9 co libowfat
	cd libowfat ; make
	sudo apt-get install zlib1g-dev
	cd ..
	git clone git://erdgeist.org/opentracker
	cd opentracker; make
	cd $HERE
	echo opentracker is at ../opentracker/opentracker
	echo sudo cp ../opentracker/opentracker /usr/local/bin
	;;
remove)	:
	echo this code is not yet ready
	if [ -d libowfat ];then
		echo libowfat has been found within ${HERE}
	fi
	echo rm -rf libowfat opentracker
	echo sudo rm /usr/local/bin/opentracker
	;;
makeenv) :
	sudo bash << EOF
	mkdir /opt/opentracker
	mkdir /opt/opentracker/bin
	mkdir /opt/opentracker/log
	mkdir /opt/opentracker/etc
EOF
	;;
esac

cd $HERE
