#!/bin/bash


conffilecopy="./postconf.out"
showparams()
{
	for p in $*
		do
			egrep ^${p} $conffilecopy 
		done
}
echo Hardening Postfix on $(hostname)
echo "   "the current parameters are,

showparams disable_vrfy inet_interfaces mynetworks smtp_helo_reqd relayhost smtp_sasl_auth_enable smtp_sasl_security_options smtp_sasl_password_maps smtp_use_tls smtp_tls_CAfile

echo ... Hardening verify and listners

#postconf -e disable_vrfy_command=yes
#postconf -e inet_interfaces=loopback-only
# mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
# postconf -e mynetworks="127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
showparams disable_vrfy inet_interfaces mynetworks 

# I am advised that there are some incoming hardening params to set

# postconf -e smtp_helo_reqd=yes
# postconf -e  relayhost=[hostname.example.org]:587

showparams smtp_helo_reqd relayhost 

# and  now sasl

echo the SASL configuration requires a passwd private file which will need,
echo "    touch, vi and pastmap"
showparams smtp_sasl_auth_enable smtp_sasl_security_options smtp_sasl_password_maps 

echo STARTTLS needs to be created.

# postconf -e smtp_use_tls=yes
# postconf -e smtp_tls_CAfile=<file name>
showparams smtp_use_tls smtp_tls_CAfile

echo $0 ends

