#!/bin/bash

# V1.0 the pre-reqs for Ubuntu 22.04

# this needs admin priviledge

sudo apt install flex bison gperf
sudo apt install expat expat1-dev libexpat1-dev

sudo apt install libcurl4-dev libcurl4-openssl-dev

sudo apt install libgtk2.0-dev
sudo apt install libcanberra-gtk-module


