#!/bin/bash

# Author: Dave Levy   Version 1.2
VER=1.2

# This script uses a bunch of standing text files to insert an rss entry into 
# an RSS file. It was intially written to create an rss file of my linkedin
# pulse feed. 

# In this version,  the output file is named in feedname var, and is 
# located in the sub folder $WDIR, the working copy is versioned using 
# a version count file called ctr.txt. These values would be good being specified 
# as CLI arguments. 

# the final publication point is held in a file link.txt

# The new snip must be held in item.txt, a standing interim version is held in
# items.xml. This contains the concatenated posts. They are then concatenated
# with head.xml and tail.xml into the new feed file. 

# is item.txt already in items.xml

WDIR="./rsslog"
CTR=${WDIR}/ctr.txt

feedname=${WDIR}/eventlog
puburl=$(cat ${WDIR}/link.txt)
echo $puburl


linelinit=5
#if [ $( cat ${WDIR}/item.txt | egrep '^<' | wc -l ) != $four ];then
	#echo "Error: diff item* ext fails"
	#exit 10
#fi
# a test on the age of item.txt would be good to.

# if not, back up the rss file and merge the *.xml files into a new rss

mv ${WDIR}/items.xml ${WDIR}/items.txt
cat ${WDIR}/item.txt ${WDIR}/items.txt > ${WDIR}/items.xml
rm ${WDIR}/items.txt

version=$( expr `cat ${CTR}` + 1 )
echo $version > ${CTR}
# linkedin.rss is the name of the new and old feed
cp ${feedname}.rss ${feedname}.rss.${version}
cat ${WDIR}/*.xml > ${feedname}.rss

# needs a publication statement.

