#!/bin/bash

# on elementary, notify-osd must be installed and the icons need to be in /usr/share/icons

# checks and reports if new version of hugo is required, uses whathugoversion

usage="check_hugoversion [-v|-h]"
# are there things to get?

case $1 in
-v)	whathugoversion ; ;;
-h)	echo $usage ; ;;
*)	whathugoversion > /dev/null 2>&1
	if [[ $? == 1 ]];then
		notify-send -i software-update-available "New packages" "hugo update avaiable, you need to run update_hugo"
		exit 1
	else
		exit
	fi
	;;
esac
	

