#!/bin/bash

# Author Dave Levy	Date 30 Aug 2016 	Version 1.2

# 			12 Nov 2022		Version: 1.3
#			14 Jan 2022		Version: 1.4

# obtains the ip address of a given ethernet device, via menu or from the cli
# the ip address is echoed via stdout

# -h help, -m menu, -d a debug mode enhanced diagnostics  or -b which allows hte naming
#	of the device. 

# i.e. using -m offers you a list of devices from which you can choose or
# -b allows the specification of the device from which the ip address is to be
# taken

# needs to run as root, could do with a clean to delete the persistance file 
# and a switch to merely cat the file

# why not use ip -4 or my showsysip script


ERROR="Error in command line arguments"
USAGE="$(basename $0) [ -h | -m | -q | -d | -b device ]"

debug=/bin/false
debugecho()
{
	[ ${debug} ] && echo $*
}

PERSISTANCE="/usr/local/etc/.myip"

while getopts "hmqdb:" arg
do
case $arg in
m)	devices=$(ifconfig -a -s | cut -f1 -d" ")
	set DEVICES

	for i in $devices
	do
		if [[ $i == "Iface" ]];then
			:
		else
			DEVICES="${DEVICES} ${i}"
		fi
	done

	echo "Select the Device Name for which IP is to be stored"
	select PORTNAME in $DEVICES
	do
		break
	done
	echo $PORTNAME set in menu mode
	;;
q)	: # quick mode
	[ -f ${PERSISTANCE} ] && cat ${PERSISTANCE}
	exit
	;;	
b)	PORTNAME=${OPTARG}
	# it would be good to test that $PORTNAME actuall named an valid device
	debugecho $PORTNAME set in batch mode reported by debug echo
	;;
d)	debug=true
	debugecho debug set to $debug, reported by debugecho
	;;
h)	echo ${USAGE}
	exit 
	;;
help)	echo ${USAGE}
	exit 
	;;
*)	echo ${ERROR}; exit 1
	;;
esac
done

#PORTNAME=enp0s8
#debugecho Portname rest to $PORTNAME by default code path
#
# write PORTNAME to a twin persistance file, so -q can report the port name

# this could be parameterised a -o flag

# we are going to make a new persistance file
rm ${PERSISTANCE}

# next test should be based on OS not arch. using my distroname function.

OSname=`whatdistro -1`

case $(arch) in
armv7l) debugecho this is an ARM system  
	SEARCHSTRING="inet"
	ifconfig $PORTNAME | grep ${SEARCHSTRING} | head -1 | cut -f2 -d"t" | cut -f2 -d" " | tee ${PERSISTANCE}
	;;
x86_64)	echo arch = x64, assume Ubuntu 22
	SEARCHSTRING="inet"
	ifconfig $PORTNAME | grep ${SEARCHSTRING} | head -1 | cut -f2 -d"t" | cut -f2 -d" " | tee ${PERSISTANCE}
	;;
*)	echo arch = else;
	SEARCHSTRING='"inet addr"'
	ifconfig $PORTNAME | grep ${SEARCHSTRING} | head -1 | cut -f2 -d":" | cut -f1 -d" " | tee ${PERSISTANCE}
	;;
esac

# on the U20 machine
# ifconfig $PORTNAME | grep "inet " | awk '{print $2}' > ${PERSISTANCE}

# if verbose, or maybe not, is this replaced by -q
# cat ${PERSISTANCE}


